version: '3.8'
services:

  auto-api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Containerfile
    container_name: auto-api
    hostname: auto-api
    networks:
      - auto-net
    ports:
      - 8080:8080
    environment:
      - PGUSER=${PGUSER:-db_admin}
      - PGPASSWORD=${PGPASSWORD:-db_password}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE:-auto_db}
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres
    restart: always
    container_name: auto-db
    hostname: db
    secrets:
      - db-password
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=postgres
    networks:
      - auto-net
    ports:
      - "5432:5432"
    volumes:
      - auto-vol:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db/seed.sh:/docker-entrypoint-initdb.d/seed.sh
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 120s
      timeout: 5s
      retries: 3

volumes:
  auto-vol:

networks:
  auto-net:
    driver: bridge

secrets:
  db-password:
    file: db/passwd.txt
